Models/Project.cs
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace BugTracker.Models
{
    public class Project
    {

        private DateTime _startDate;
        private DateTime _endDate;
        private DateTime _created;
        public int Id { get; set; }

        public int CompanyId { get; set; }

        [Required]
        public string? Name { get; set; }


        [Required]
        public string? Description { get; set; }

        [DataType(DataType.Date)]
        public DateTime Created { get { return _created; } set { _created = value.ToUniversalTime(); }  }

        [DataType(DataType.Date)]
        public DateTime StartDate { get { return _startDate; } set { _startDate = value.ToUniversalTime(); } }

        [DataType(DataType.Date)]
        public DateTime EndDate { get { return _endDate; } set { _endDate = value.ToUniversalTime(); } }

        public int ProjectPriorityId { get; set; }

        [NotMapped]
        public IFormFile? ImageFile { get; set; } //doesn't get stored in db but the 2 below props do
        public byte[]? ImageData { get; set; }
        public string? ImageType { get; set; }
        public bool Archived { get; set; }

        //Navigation Properties

        public virtual Company? Company { get; set; }

        public virtual ProjectPriority? ProjectPriority { get; set; }

        public virtual ICollection<BTUser> Members { get; set; } = new HashSet<BTUser>();

        public virtual ICollection<Ticket> Tickets { get; set; } = new HashSet<Ticket>();


    }
}

Models/ViewModel/AssignPMViewModel.cs
using Microsoft.AspNetCore.Mvc.Rendering;

namespace BugTracker.Models.ViewModel
{
    public class AssignPMViewModel
    {
        public int ProjectId { get; set; }
        public string? ProjectName { get; set; }
        public SelectList? PMList { get; set; }
        public string? PMId { get; set; }
    }
}

Controllers/ProjectsController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using BugTracker.Data;
using BugTracker.Models;
using Microsoft.AspNetCore.Identity;
using BugTracker.Services.Interfaces;
using BugTracker.Models.ViewModel;
using BugTracker.Data.Enums;
using BugTracker.Services;
using Microsoft.AspNetCore.Authorization;
using System.Data;

namespace BugTracker.Controllers
{
    public class ProjectsController:BTBaseController
    {
        private readonly ApplicationDbContext _context;
        private readonly UserManager<BTUser> _userManager;
        private readonly IImageService _imageService;
        private readonly IBTProjectService _projectService;
        private readonly IBTRolesService _rolesService;
		private readonly IBTTicketService _ticketService;



		public ProjectsController(ApplicationDbContext context, UserManager<BTUser> userManager, IImageService imageService, IBTProjectService projectService, IBTRolesService rolesService, IBTTicketService ticketService)
		{
			_context = context;
			_userManager = userManager;
			_imageService = imageService;
			_projectService = projectService;
			_rolesService = rolesService;
			_ticketService = ticketService;
		}

        // GET: Projects
        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> Index()
        {
            IEnumerable<Project> projects = await _projectService.GetAllProjectsByCompanyIdAsync(_companyId);
            return View(projects);
        }

        // GET: Assign PM 

        [Authorize(Roles ="Admin")]
        [HttpGet]
        public async Task<IActionResult> AssignProjectManager(int? id)
         {
            if(id == null)
            {
                return NotFound();
            }

            Project? project = await _projectService.GetProjectByIdAsync(id, _companyId);

            if(project == null)
            {
                return NotFound();
            }

            //Get list of project managers
            IEnumerable<BTUser> projectManagers = await _rolesService
                                                    .GetUsersInRoleAsync(nameof(BTRoles.ProjectManager), _companyId);

            BTUser? currentPM = await _projectService.GetProjectManagerAsync(id);

            AssignPMViewModel viewModel = new()
            {
                ProjectId = project.Id,
                ProjectName = project.Name,
                PMList = new SelectList(projectManagers, "Id", "FullName", currentPM?.Id),
                PMId = currentPM?.Id,
            };

            return View(viewModel);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles ="Admin")]
        public async Task<IActionResult> AssignProjectManager(AssignPMViewModel viewModel)
        {
            if (!string.IsNullOrEmpty(viewModel.PMId))
            {
                if (await _projectService.AddProjectManagerAsync(viewModel.PMId, viewModel.ProjectId))
                {
                    return RedirectToAction(nameof(Details), new { id = viewModel.ProjectId });

                }
                else
                {
                    ModelState.AddModelError("PMId", " Error assigning PM.");
                }
            ModelState.AddModelError("PMId", "No Project Manager Chosen. Please select a PM.");

            }

            IEnumerable<BTUser> projectManagers = await _rolesService
                                                    .GetUsersInRoleAsync(nameof(BTRoles.ProjectManager), _companyId);

            BTUser? currentPM = await _projectService.GetProjectManagerAsync(viewModel.ProjectId);

            viewModel.PMList = new SelectList(projectManagers, "Id", "FullName", currentPM?.Id);

            return View(viewModel);
        }

        [Authorize(Roles = "Admin,ProjectManager")]
        [HttpGet]
        public async Task<IActionResult> AssignProjectMembers(int? id)
        {
            if(id == null)
            {
                return NotFound();
            }

            Project? project = await _projectService.GetProjectByIdAsync(id, _companyId);

            if (project == null)
            {
                return NotFound();
            }

            List<BTUser> submitters = await _rolesService.GetUsersInRoleAsync(nameof(BTRoles.Submitter), _companyId);
            List<BTUser> developers = await _rolesService.GetUsersInRoleAsync(nameof(BTRoles.Developer), _companyId);

            List<BTUser> usersList = submitters.Concat(developers).ToList();

            IEnumerable<string> currentMembers = project.Members.Select(u => u.Id);

            ProjectMembersViewModel viewModel = new()
            {
                Project = project,
                UsersList = new MultiSelectList(usersList, "Id", "FullName", currentMembers)
            };




                return View(viewModel);
        }

        [Authorize(Roles = "Admin,ProjectManager")]
        [HttpPost]
        public async Task<IActionResult> AssignProjectMembers(ProjectMembersViewModel viewModel)
        {
            if(viewModel.SelectedMembers != null)
            {
                await _projectService.RemoveMembersFromProjectAsync(viewModel.Project?.Id, _companyId);
                await _projectService.AddMembersToProjectAsync(viewModel.SelectedMembers,
                    viewModel.Project?.Id, _companyId);

                return RedirectToAction(nameof(Details), new { id = viewModel.Project?.Id });

            }


            viewModel.Project = await _projectService.GetProjectByIdAsync(viewModel.Project?.Id, _companyId);

            //Handle the error
            ModelState.AddModelError("SelectedMemebers", "No Users chosen. Please select Users!");

            List<BTUser> submitters = await _rolesService.GetUsersInRoleAsync(nameof(BTRoles.Submitter), _companyId);
            List<BTUser> developers = await _rolesService.GetUsersInRoleAsync(nameof(BTRoles.Developer), _companyId);

            List<BTUser> usersList = submitters.Concat(developers).ToList();

            IEnumerable<string> currentMembers = viewModel.Project!.Members.Select(u => u.Id);
            viewModel.UsersList = new MultiSelectList(usersList, "Id", "FullName", currentMembers);

            return View(viewModel);
        }


        [Authorize(Roles = "Admin,ProjectManager")]

        // GET: Projects/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.Projects == null)
            {
                return NotFound();
            }

            Project? project = await _projectService.GetProjectDetailsAsync(id);

       
            if (project == null)
            {
                return NotFound();
            }

            return View(project);
        }

        [Authorize(Roles = "Admin,ProjectManager")]
        // GET: Projects/Create
        public IActionResult Create()
        {
            ViewData["ProjectPriorityId"] = new SelectList(_context.ProjectPriorities, "Id", "Name");
            return View();
        }

		// POST: Projects/Create
		// To protect from overposting attacks, enable the specific properties you want to bind to.
		// For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
		[Authorize(Roles = "Admin,ProjectManager")]
		[HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Name,Description,Created,StartDate,EndDate,Selected,Archived,ProjectPriorityId")] Project project)
        {
            //do we provide projectpriorityId to?
            //get user from user manager and get companyId

            ModelState.Remove("CompanyId");

            if (ModelState.IsValid)
            {
                BTUser? user = await _userManager.GetUserAsync(User);

                //set Company Id, get from user
                project.CompanyId = user!.CompanyId;

                //Set Date
                project.Created = DateTime.Now;

                //Set the Image data if one has been choosen
                if (project.ImageFile != null)
                {
                    //Create the Image Service
                    //1.Convert the field to byte array and assign it to the ImageData
                    project.ImageData = await _imageService.ConvertFileToByteArrayAsync(project.ImageFile);
                    //2.Assign the ImageType based on the choosen file
                    project.ImageType = project.ImageFile.ContentType;
                    // contact.ImageData = contact.ImageFile
                }

                _context.Add(project);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["CompanyId"] = new SelectList(_context.Companies, "Id", "Name", project.CompanyId);
            ViewData["ProjectPriorityId"] = new SelectList(_context.ProjectPriorities, "Id", "Id", project.ProjectPriorityId);
            return View(project);
        }

        [Authorize(Roles = "Admin,ProjectManager")]

        // GET: Projects/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.Projects == null)
            {
                return NotFound();
            }

            var project = await _context.Projects.FindAsync(id);

            if (project == null)
            {
                return NotFound();
            }
            ViewData["ProjectPriorityId"] = new SelectList(_context.ProjectPriorities, "Id", "Name", project.ProjectPriorityId);
            return View(project);
        }

        // POST: Projects/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [Authorize(Roles = "Admin,ProjectManager")]
        [HttpPost]
        [ValidateAntiForgeryToken]

Views/Projects/Archive.cshtml
@model Project

@{
    ViewData["Title"] = "Delete";
}

<h4 class="mt-5">Project</h4>

<label>Are you sure you want to archive this project?</label>
<div>

    <div class=" col-lg-6 ">
        <div class="card custom-card">
            <div class="card-body">
                <div class="card-item">
                    <div class="card-item-icon card-icon">
                        <svg class="text-primary" xmlns="http://www.w3.org/2000/svg"
                             enable-background="new 0 0 24 24" height="24"
                             viewBox="0 0 24 24" width="24">
                            <g>
                                <rect height="14" opacity=".3" width="14" x="5" y="5" />
                                <g>
                                    <rect fill="none" height="24" width="24" />
                                    <g>
                                        <path d="M19,3H5C3.9,3,3,3.9,3,5v14c0,1.1,0.9,2,2,2h14c1.1,0,2-0.9,2-2V5C21,3.9,20.1,3,19,3z M19,19H5V5h14V19z" />
                                        <rect height="5" width="2" x="7" y="12" />
                                        <rect height="10" width="2" x="15" y="7" />
                                        <rect height="3" width="2" x="11" y="14" />
                                        <rect height="2" width="2" x="11" y="10" />
                                    </g>
                                </g>
                            </g>
                        </svg>
                    </div>
                    <div class="card-item-title mb-2">
                        <label class="main-content-label tx-13 font-weight-bold mb-1">
                            @Model.Name
                        </label>
                        <span class="d-block tx-12 mb-0 text-muted">
                            @Model.Created
                        </span>
                    </div>
                    <div class="card-item-body">
                        <div class="card-item-stat">
                            <h4 class="font-weight-bold"> @Model.Description</h4>

                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>


    <form asp-action="post">
        <input type="hidden" asp-for="Id" />
        <a class="btn btn-danger" asp-action="Details" asp-controller="Projects" asp-route-id="@Model.Id">  Archive </a> |
        <a asp-action="Details" asp-route-id="@Model.Id">Back to Project</a>
    </form>
</div>

Views/Projects/ArchivedProjects.cshtml
@model IEnumerable<BugTracker.Models.Project>
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}

<div class="xfont-weighteighteightgetainer-fluid">
    <div class="row gy-2">
        <div class="col-md-12 col">
            <div class="row col-cols-2 mt-5">
                <div class="card custom-card col m-1 p-2">
                    <div class="card-body">

                        <label class="main-content-label mb-2 mt-2" style="font-size:medium">
                            Archived Projects
                        </label>


                    </div>
                </div>
            </div>
        </div>
    </div>
</div>



<div class="container-fluid">

    <div class="col-md-12 col">
        <div class="mt-5">
            <div class="card">
                <div class="card-header">
                    
                </div>
                <div class="card custom-card">
                    <div class="card-body">
                        <div class="table-responsive">
                            <table class="table table-bordered table-striped" id="example2">
                                <thead class="">
                                    <tr>
                                        <th>
                                            @Html.DisplayNameFor(model => model.Name)
                                        </th>
                                        <th>
                                            @Html.DisplayNameFor(model => model.Created)
                                        </th>
                                        <th>
                                            @Html.DisplayNameFor(model => model.StartDate)
                                        </th>
                                        <th>
                                            @Html.DisplayNameFor(model => model.EndDate)
                                        </th>
                                        <th>
                                            @Html.DisplayNameFor(model => model.Archived)
                                        </th>
                                        <th>
                                            @Html.DisplayNameFor(model => model.Company)
                                        </th>
                                        <th>
                                            @Html.DisplayNameFor(model => model.ProjectPriority)
                                        </th>
                                        <th></th>
                                    </tr>
                                </thead>
                                <tbody>
                                    @foreach (var item in Model)
                                    {
                                        <tr>
                                            <td>
                                                @Html.DisplayFor(modelItem => item.Name)
                                            </td>
                                            <td>
                                                @Html.DisplayFor(modelItem => item.Created)
                                            </td>
                                            <td>
                                                @Html.DisplayFor(modelItem => item.StartDate)
                                            </td>
                                            <td>
                                                @Html.DisplayFor(modelItem => item.EndDate)
                                            </td>
                                            <td>
                                                @Html.DisplayFor(modelItem => item.Archived)
                                            </td>
                                            <td>
                                                @Html.DisplayFor(modelItem => item.Company!.Name)
                                            </td>
                                            <td>
                                                @Html.DisplayFor(modelItem => item.ProjectPriority!.Id)
                                            </td>
                                            <td>
                                                @if (item.Archived == true)
                                                {
                                                    <a class="btn btn-md bg-success" asp-action="Restore" asp-route-id="@item.Id">Restore</a>
                                                }
                                                else
                                                {
                                                    <a class="btn btn-md bg-danger" asp-action="Archive" asp-route-id="@item.Id">Archive</a>
                                                }

                                                |
                                                <a class="btn btn-md bg-primary" asp-action="Edit" asp-route-id="@item.Id">Edit</a> |
                                                <a class="btn btn-md bg-info" asp-action="Details" asp-route-id="@item.Id">Details</a> |
                                                <a class="btn btn-md bg-warning" asp-action="AssignProjectManager" asp-route-id="@item.Id">Assign PM</a>

                                            </td>
                                        </tr>
                                    }
                                </tbody>
                            </table>
                        </div>

                    </div>
                </div>
            </div>

        </div>
    </div>


</div>

Views/Projects/AssignPM.cshtml
@model BugTracker.Models.ViewModel.AssignPMViewModel

@{
    ViewData["Title"] = "Assign Project Manager";
}
<div class="d-flex justify-content-center mt-5 flex-column align-items-center">
    <h3 class="my-5">Assign Project Manager</h3>
    <div class="card">
        <div class="card-header">
            <div class="card-title">@Model.ProjectName</div>
        </div>
        <div class="card-body">
            <form asp-action="AssignPM" asp-controller="Projects" method="post" class="d-flex flex-column">
                <input type="hidden" asp-for="ProjectId" />
                <select asp-items="Model.PMList" asp-for="PMId">
                    <option value="">Unassigned</option>
                </select>
                <span asp-validation-for="PMId" class="text-danger"></span>
                <button type="submit" class="btn btn-primary my-3">Save</button>
                @*<a asp-action="Details" asp-route-id="@Model.ProjectId" class="btn btn-secondary">Cancel</a>*@
                <a asp-action="Index" class="btn btn-secondary">Cancel</a>
            </form>
        </div>
    </div>
</div>

Views/Projects/AssignProjectManager.cshtml
@model BugTracker.Models.ViewModel.AssignPMViewModel

@{
    ViewData["Title"] = "Assign Project Manager";
}
<div class="d-flex justify-content-center mt-5 flex-column align-items-center">
    <h3 class="my-5">Assign Project Manager</h3>
    <div class="card">
        <div class="card-header">
            <div class="card-title">@Model.ProjectName</div>
        </div>
        <div class="card-body">
            <form asp-action="AssignProjectManager" asp-controller="Projects" method="post" class="d-flex flex-column">
                <input type="hidden" asp-for="ProjectId" />
                <select asp-items="Model.PMList" asp-for="PMId">
                    <option value="">Unassigned</option>
                </select>
                <span asp-validation-for="PMId" class="text-danger"></span>
                <button type="submit" class="btn btn-primary my-3">Save</button>
                @*<a asp-action="Details" asp-route-id="@Model.ProjectId" class="btn btn-secondary">Cancel</a>*@
                <a asp-action="Index" class="btn btn-secondary">Cancel</a>
            </form>
        </div>
    </div>
</div>

Views/Projects/AssignProjectMembers.cshtml
@model ProjectMembersViewModel

@{
    ViewData["Title"] = "Assign Project Members";
}
<div class="d-flex justify-content-center mt-5 flex-column align-items-center">
    <h3 class="my-5">Assign Project Members</h3>
    <div class="card">
        <div class="card-header">
            <div class="card-title">@Model.Project!.Name</div>
        </div>
        <div class="card-body">
            <form asp-action="AssignProjectMembers" asp-controller="Projects" method="post" class="d-flex flex-column">
                <input type="hidden" asp-for="Project!.Id" />
                <select asp-items="Model.UsersList" asp-for="SelectedMembers" class="form-control" 
                multiple required>
                </select>
                <span asp-validation-for="SelectedMembers" class="text-danger"></span>
                <button type="submit" class="btn btn-primary my-3">Save</button>
                <a asp-action="Details" asp-route-id="@Model.Project!.Id" class="btn btn-secondary">Cancel</a>
            </form>
        </div>
    </div>
</div>

Views/Projects/Create.cshtml
@using BugTracker.Enums;
@using BugTracker.Services.Interfaces;
@model BugTracker.Models.Project
@inject IImageService _ImageService
@inject IBTFileService _fileService

@{
    ViewData["Title"] = "Create";
}


<label class="main-content-label mb-2 mt-2" style="font-size:medium">
    Create Project <i class="si si-plus p-1"></i>
</label>

<hr />

<div class="row row-sm">

    <div class="col-lg-6 col-md-12">
        <div class="card custom-card">
            <div class="card-body">
                <form asp-action="Create">
                    <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                    <input type="hidden" asp-for="Created" />
                    <div class="">
                        <div class="row row-xs align-items-center mg-b-20">
                            <div class="col-md-4">
                                <label asp-for="Name" class="control-label"></label>
                            </div>
                            <div class="col-md-8 mg-t-5 mg-md-t-0">
                                <input asp-for="Name" class="form-control" />
                                <span asp-validation-for="Name" class="text-danger"></span>
                            </div>
                        </div>
                        <div class="row row-xs align-items-center mg-b-20">
                            <div class="col-md-4">
                                <label asp-for="Description" class="control-label"></label>
                            </div>
                            <div class="col-md-8 mg-t-5 mg-md-t-0">
                                <input asp-for="Description" class="form-control" />
                                <span asp-validation-for="Description" class="text-danger"></span>
                            </div>
                        </div>
                        <div class="row row-xs align-items-center mg-b-20">
                            <div class="col-md-4">
                                <label asp-for="StartDate" class="control-label"></label>
                            </div>
                            <div class="col-md-8 mg-t-5 mg-md-t-0">
                                <input asp-for="StartDate" class="form-control" />
                            </div>
                        </div>
                        <div class="row row-xs align-items-center mg-b-20">
                            <div class="col-md-4">
                                <label asp-for="EndDate" class="control-label"></label>
                            </div>
                            <div class="col-md-8 mg-t-5 mg-md-t-0">
                                <input asp-for="EndDate" class="form-control" />
                            </div>
                        </div>
                        <div class="row row-xs align-items-center mg-b-20">
                            <div class="col-md-4">
                                <label asp-for="ProjectPriorityId" class="control-label"></label>
                            </div>
                            <div class="col-md-8 mg-t-5 mg-md-t-0">

                                <select asp-for="ProjectPriorityId" class="form-control" asp-items="ViewBag.ProjectPriorityId"></select>
                            </div>
                        </div>
                        <div class="row row-xs align-items-center mg-b-20">
                            <div class="col-md-4">
                                <img id="contactImage" class="img-fluid border rounded-3 mb-2" style="max-height: 150px;"
                                     src="@_fileService.ConvertByteArrayToFile(Model?.ImageData!,Model?.ImageType!,DefaultImage.ProjectImage)" style="height:80px;width:80px">
                            </div>
                            <div class="col-md-8 mg-t-5 mg-md-t-0">
                                <input asp-for="ImageFile" class="form-control mt-3 pt-2" accept=".png,.jpg,.jpeg,.gif"
                                       onchange="document.getElementById('contactImage').src= window.URL.createObjectURL(this.files[0])" />
                                <span asp-validation-for="ImageFile" type="file" class="text-danger"></span>
                            </div>
                        </div>
                        <div class="row row-xs align-items-center mg-b-20">
                            <div class="col-md-4">
                                <label class="form-check-label">
                                    <input class="form-check-input" asp-for="Archived" /> @Html.DisplayNameFor(model => model.Archived)
                                </label>
                            </div>
                        </div>



                        <div class="form-group row justify-content-end mb-0">
                            <div class="col-md-8 ps-md-2">
                                <input type="submit" value="Create" class="btn btn-primary" />
                            </div>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>

<div>
    <div>
        <a asp-action="Index"><span class="badge bg-dark">  Back to Project List </</span></a>
    </div>
</div>

@section Scripts {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
}

Views/Projects/Restore.cshtml
@model Project

@{
    ViewData["Title"] = "Delete";
}

<h4 class="mt-5">Project</h4>

<label>Are you sure you want to restore this project?</label>
<div>

    <div class=" col-lg-6 ">
        <div class="card custom-card">
            <div class="card-body">
                <div class="card-item">
                    <div class="card-item-icon card-icon">
                        <svg class="text-primary" xmlns="http://www.w3.org/2000/svg"
                             enable-background="new 0 0 24 24" height="24"
                             viewBox="0 0 24 24" width="24">
                            <g>
                                <rect height="14" opacity=".3" width="14" x="5" y="5" />
                                <g>
                                    <rect fill="none" height="24" width="24" />
                                    <g>
                                        <path d="M19,3H5C3.9,3,3,3.9,3,5v14c0,1.1,0.9,2,2,2h14c1.1,0,2-0.9,2-2V5C21,3.9,20.1,3,19,3z M19,19H5V5h14V19z" />
                                        <rect height="5" width="2" x="7" y="12" />
                                        <rect height="10" width="2" x="15" y="7" />
                                        <rect height="3" width="2" x="11" y="14" />
                                        <rect height="2" width="2" x="11" y="10" />
                                    </g>
                                </g>
                            </g>
                        </svg>
                    </div>
                    <div class="card-item-title mb-2">
                        <label class="main-content-label tx-13 font-weight-bold mb-1">
                            @Model.Name
                        </label>
                        <span class="d-block tx-12 mb-0 text-muted">
                            @Model.Created
                        </span>
                    </div>
                    <div class="card-item-body">
                        <div class="card-item-stat">
                            <h4 class="font-weight-bold"> @Model.Description</h4>

                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>


    <form asp-action="post">
        <input type="hidden" asp-for="Id" />
        <a class="btn btn-success" asp-action="Details" asp-controller="Projects" asp-route-id="@Model.Id">  Restore </a> |
        <a asp-action="Details" asp-route-id="@Model.Id">Back to Project</a>
    </form>
</div>